### ISSUE TITLE
CPU usage issue of the Rabbit Service

### ISSUE THREAD

**Issue by jing-li-rocos** [houseofcat/turbocookedrabbit#10]
The Rabbit Service start the auto publishing by default. The auto publishing also depends on the SleepOnIdle number to setup the loop. If the SleepOnIdle is very small, the CPU usage will be really high. Suggest to use channel to feed the auto publish rather than the for loop.

**Comment by houseofcat** [comment]
This was actually a performance enhancement, I am not sure I sold on it, but when <- wait to receive, it is more costly than default action of adding time.Sleep().

I am arguing over microseconds but it just became routine for me to put a default: sleep in all of my channel receive loops.

My suggestion is to set the SleepOnIdle to at least 1 ms, 0 means its disabled and it will loop as fast as Golang is capable looking for messages to publish.

I may revisit this in the future just to simplify usage even more and take the small "hit" on performance.

**Comment by houseofcat** [comment]
With your other PR/Issue, I have added a quick func and a new ConnectionPool creation method.

```golang
NewConnectionPoolWithErrorHandler(config *PoolConfig, errorHandler func(error)) (*ConnectionPool, error)
```

Very straightforward to use, here is an example.

```golang
func TestCreateConnectionPoolWithErrorHandler(t *testing.T) {
	defer leaktest.Check(t)() // Fail on leaked goroutines.

	seasoning, err := tcr.ConvertJSONFileToConfig("badtest.json")
	if err != nil {
		return
	}

	cp, err := tcr.NewConnectionPoolWithErrorHandler(seasoning.PoolConfig, errorHandler)
	assert.Nil(t, cp)
	assert.Error(t, err)

	cp.Shutdown()
	TestCleanup(t)
}

func errorHandler(err error) {
	fmt.Println(err)
}
```

**Comment by jing-li-rocos** [comment]
Thanks so much, this is a great improvement.

**Comment by jing-li-rocos** [comment]
> This was actually a performance enhancement, I am not sure I sold on it, but when <- wait to receive, it is more costly than default action of adding time.Sleep().
> 
> I am arguing over microseconds but it just became routine for me to put a default: sleep in all of my channel receive loops.
> 
> My suggestion is to set the SleepOnIdle to at least 1 ms, 0 means its disabled and it will loop as fast as Golang is capable of rapidly trying to look for messages to publish.
> 
> I may revisit this in the future just to simplify usage even more and take the small "hit" on performance.

Cool, thanks for your advise.

**Comment by houseofcat** [comment]
I am going to close out this issue for now, but I will think about ways of writing easier to use out of the box - or have better documentation.

Any new issues please open them here as you run into them.
