### ISSUE TITLE
how can i push message with priotity field?

### ISSUE THREAD

**Issue by dfelici87** [houseofcat/turbocookedrabbit#14]
Hi,

How can I set a priority of message (https://www.rabbitmq.com/priority.html)?

Can you add "priotiry" field into Envelope struct of letter.go file?

Thanks

**Comment by houseofcat** [comment]
Looks like I overlooked this when I did v2.

Added.

Fixed with https://github.com/houseofcat/turbocookedrabbit/commit/c7a5e9365a4ea0247c36ccc9e597d81348c96915

**Comment by dfelici87** [comment]
thanks
