### ISSUE TITLE
How to set the correlation ID?

### ISSUE THREAD

**Issue by clalos** [houseofcat/turbocookedrabbit#26]
Hello,
first of all thanks for the amazing work. I can't find a way to set the correlation ID of the underlying `amqp.Publishing` struct. It seems not supported by the configuration.

```
// Letter contains the message body and address of where things are going.
type Letter struct {
	LetterID   uuid.UUID
	RetryCount uint32
	Body       []byte
	Envelope   *Envelope
}

// Envelope contains all the address details of where a letter is going.
type Envelope struct {
	Exchange     string
	RoutingKey   string
	ContentType  string
	Mandatory    bool
	Immediate    bool
	Headers      amqp.Table
	DeliveryMode uint8
	Priority     uint8
}
```

--- Update
It would be nice to set the `amqp.Publishing.Type` as well.

**Comment by houseofcat** [comment]
This was solved in release `v2.1.4`

Details:
https://github.com/houseofcat/turbocookedrabbit/pull/27
