### ISSUE TITLE
Can you return Header in Message struct?

### ISSUE THREAD

**Issue by dfelici87** [houseofcat/turbocookedrabbit#5]
Hello,

Great library!!!
I need to read the header of message that i received in a queue(for dead letter exchange into the message header rabbitmq write some util information).

Can you add a message Header in models.Message struct?
example :
type Message struct {
	IsAckable   bool
        Headers     amqp.Table
	Body        []byte
	deliveryTag uint64
	amqpChan    *amqp.Channel
}

Thanks in advance.

**Comment by houseofcat** [comment]
Absolutely, will get to it asap.

**Comment by houseofcat** [comment]
You should be good to go in v2.0.2.

Letter headers should have been publishing but added RabbitService generic publishes to support headers fields.

Consumers are now persisting Headers and providing access to them in ReceivedData structs.
