### ISSUE TITLE
Error when i try to use library version >= 2.X.X

### ISSUE THREAD

**Issue by dfelici87** [houseofcat/turbocookedrabbit#7]
When I try to use a library version v2.0.6 but I get this error:
_require github.com/houseofcat/turbocookedrabbit: version "v2.0.6" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2_

I use go 1.13, how can i use the last version of library?...

thanks in advance

**Comment by houseofcat** [comment]
Try changing your imports to  `github.com/houseofcat/turbocookedrabbit/v2`. That's unfortunately required for v2+ in golang.

**Comment by dfelici87** [comment]
works! thanks
